# This file will be joined with docker-compose.app.yml from dcape
# See https://github.com/dopos/dcape

services:
  # This service will extend code from dcape
  app:
    ports:
      - ${SERVICE_PORT}:53/udp
      - ${SERVICE_PORT}:53/tcp
    volumes:
      - ./unbound:/opt/unbound/etc/unbound
    labels:
      - traefik.enable=false
